# Generated by Django 5.0.4 on 2024-04-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('wallet', '0002_wallet_created_at_wallet_currency_wallet_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.cirkulauser'),
        ),
    ]
